server:
  port: 8082

spring:
  jpa:
    open-in-view: false

  config:
    import:
      - optional:application-local.yml
      - optional:application-docker.yml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
