spring:
  config:
    activate:
      on-profile: local

  # 로컬 데이터베이스 설정 (Docker 사용)
  datasource:
    url: jdbc:postgresql://localhost:5433/unear
    username: unear
    password: Ureca2Unear!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
